print('Hi, how are you \nI am a small bot created by a BYU student called Freeman \nI want to interact with you')
print()
print('Thank you for your, time \nI will be asking you a few questions \nPlease respond on the prompt below')
print()
name=input('What is your name?\n: ')
print()
print('Thank you for that', name)
print()
fav_color=input('Now, what is your favourate color?\n: ' )
print()
print('Congradulations', name, 'your favourate color is ',fav_color)
print()
print('Thank you very much with interacting with this Bot, please have a pleasant day!!!!!!!!!!!!')